homepage:
  url:   /
  param: { module: foobar, action: firstFragment }

second:
  url:  /esi/second-fragment
  param: { module: foobar, action: secondFragment }

third:
  url: /esi/third-fragment
  param: { module: foobar, action: thirdFragment }
